넘파이 ndarray 개요

In [28]:
import numpy as np
array1=np.array([1,2,3])
print('array1 type:',type(array1))
print('array1 array 형태:',array1.shape)

array2=np.array([[1,2,3],[2,3,4]])
print('array2 type:',type(array2))
print('array2 array 형태:',array2.shape)

array3=np.array([[1,2,3]])
print('array3 type:',type(array3))
print('array3 array 형태:',array3.shape)

array1 type: <class 'numpy.ndarray'>
array1 array 형태: (3,)
array2 type: <class 'numpy.ndarray'>
array2 array 형태: (2, 3)
array3 type: <class 'numpy.ndarray'>
array3 array 형태: (1, 3)


In [29]:
print('array1:{0}차원,array2:{1}차원,array3:{2}차원'.format(array1.ndim,array2.ndim,array3.ndim))

array1:1차원,array2:2차원,array3:2차원


ndarray 의 데이터 타입

In [30]:
list1=[1,2,3]
print(type(list1))
array1=np.array(list1)
print(type(array1))
print(array1,array1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int32


In [31]:
list2=[1,2,'test']
array2=np.array(list2)
print(array2,array2.dtype)

list3=[1,2,3.0]
array3=np.array(list3)
print(array3,array3.dtype)

['1' '2' 'test'] <U11
[1. 2. 3.] float64


In [32]:
#int32->float64 변환 
array_int=np.array([1,2,3])
array_float=array_int.astype('float64')
print(array_float,array_float.dtype)

array_int1=array_float.astype('int32')
print(array_int1,array_int1.dtype)

array_float1=np.array([1.1,2.1,3.1])
array_int2=array_float1.astype('int32')
print(array_int2,array_int2.dtype)

[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


ndarray를 편리하게 생성하기 -arrange,zeros,ones

In [33]:
sequence_array=np.arange(10)
print(sequence_array)
print(sequence_array.dtype,sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int32 (10,)


In [36]:
zero_array=np.zeros((3,2),dtype='int32')
print(zero_array)
print(zero_array.dtype,zero_array.shape)

one_array=np.ones((3,2))
print(one_array)
print(one_array.dtype,one_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


ndarray의 차원과 크기를 변경하는 reshape()

In [38]:
array1=np.arange(10)
print('array1:\n',array1)

array2=array1.reshape(2,5)
print('array2:\n',array2)

array3=array1.reshape(5,2)
print('array3:\n',array3)

#array1.reshape(4,3) 오류 남 ->같은 크기가 아니라서

array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [39]:
array1=np.arange(10)
print(array1)
array2=array1.reshape(-1,5)
print('array2 shape:',array2.shape)
array3=array1.reshape(5,-1)
print('array3 shape:',array3.shape)

[0 1 2 3 4 5 6 7 8 9]
array2 shape: (2, 5)
array3 shape: (5, 2)


In [42]:
array1=np.arange(8)
array3d=array1.reshape((2,2,2))
print('array3d:\n',array3d.tolist())

#3차원 ndarray를 2차원 ndarray로 변환
array5=array3d.reshape(-1,1)
print('array5:\n',array5.tolist())
print('array5 shape:',array5.shape)

#1차원 ndarray를 2차원 ndarray로 변환
array6=array1.reshape(-1,1)
print('array6:\n',array6.tolist())
print('array6 shape:',array6.shape)

array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
array5:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array5 shape: (8, 1)
array6:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6 shape: (8, 1)


넘파이의 ndarray의 데이터 세트 선택하기- 인덱싱(indexing)

In [ ]:
#1부터 9까지의 1차원 ndarray 생성
array1=np.arrange(start=1,stop=10)
